name: Docker CI Learning - KUCL 
on:
  push:
jobs:
  docker_1:
    runs-on: ubuntu-latest 
      #labels: kucl22 
         
    steps:
      -
        name: Set up QEMU test
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/sanket:actions
  deploy:
    needs: docker_1
    name: k8s deployment 
    runs-on: 
      labels: sanket
    steps:
      - name: create deployment
        run: mkdir ${HOME}/.kube
        run: echo ${{MYKUBECONFIG}} | base64  --decode > ${HOME}./kube/config
        run: kubectl create deployment githubaction --image=docker.io/httpd
